### ISSUE TITLE
Intellij coder not starting (Websocket connections fails)

### ISSUE THREAD

**Issue by cromero251290** [coder/enterprise-images#196]
![2](https://user-images.githubusercontent.com/106993360/217522133-5f049a6b-5a3e-4a4b-8b1f-3904c507561e.png)
![3](https://user-images.githubusercontent.com/106993360/217522178-def1bda6-216c-4161-8c99-fc8ea98f4f1c.png)
Hi, we are trying to launch the Intellij IDE by extending codercom/enterprise-intellij:ubuntu image but for some reason the launch fails. This is the error message that is displayed in  the browser console.

Error: Cannot find module './lib/encoding'
Require stack:
- /var/tmp/coder/code-server/node_modules/negotiator/index.js
- /var/tmp/coder/code-server/node_modules/accepts/index.js
- /var/tmp/coder/code-server/node_modules/compression/index.js
- /var/tmp/coder/code-server/out/node/app.js
- /var/tmp/coder/code-server/out/node/main.js
- /var/tmp/coder/code-server/out/node/entry.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.require._load (/var/tmp/coder/code-server/out/node/plugin.js:50:74)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadModule (/var/tmp/coder/code-server/node_modules/negotiator/index.js:108:16)
    at Negotiator.encodings (/var/tmp/coder/code-server/node_modules/negotiator/index.js:56:28)
    at Accepts.encoding.Accepts.encodings (/var/tmp/coder/code-server/node_modules/accepts/index.js:143:26)
    at ServerResponse.onResponseHeaders (/var/tmp/coder/code-server/node_modules/compression/index.js:178:27)
    at ServerResponse.writeHead (/var/tmp/coder/code-server/node_modules/on-headers/index.js:35:16)

**Comment by johnstcn** [comment]
Hi @cromero251290, can you provide a sample Dockerfile that reproduces this behaviour?

Can you also share on which version of Coder you are seeing this behaviour?

**Comment by cromero251290** [comment]
Hi thanks for reply. 
----------------------------------------------------------------------------------------------------------
coder version v1.32.1 go1.18.2b7 linux/amd64 c5a98192e44988354dd6d9eae1dd4288e6cd5294
------------------------------------------------------------------------------------------------------------
FROM codercom/enterprise-intellij:ubuntu


USER root

# Install Java 8
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:openjdk-r/ppa && \
    apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/oracle-jdk8-installer

# Maven environment
RUN mkdir -p /usr/local/apache-maven

RUN wget https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.3.9/apache-maven-3.3.9-bin.tar.gz && tar -xzvf apache-maven-3.3.9-bin.tar.gz -C /usr/local/apache-maven


ENV M2_HOME=/usr/local/apache-maven/apache-maven-3.3.9
ENV M2=$M2_HOME/bin
ENV PATH=$M2:$PATH

COPY configure /coder/configure
# Maven custome settings
COPY settings.xml /coder/.m2/settings.xml

RUN  chmod a+x /coder/configure

USER coder

**Comment by johnstcn** [comment]
Hi @cromero251290,

If you are using the most recent version of the image, please note that [the version of Coder you are using](https://coder.com/docs/v1/latest/changelog/1.32.1) does not have the most recent version of Jetbrains Projector bundled. The [subsequent patch release 1.32.3](https://coder.com/docs/v1/latest/changelog/1.32.3) does include these.

Please also note that [Jetbrains has suspended development of Projector](https://lp.jetbrains.com/projector/).
